export const NETWORK_STATUS_CHANGED = 'NETWORK_STATUS_CHANGED';
export const LOADING_FULL ='LOADING_FULL';
export const LOADING_COMPLETED ='LOADING_COMPLETED';
export const RESET_REFRESH_LOADING = 'RESET_REFRESH_LOADING';
export const LOGIN_RESPONSE ='LOGIN_RESPONSE';
export const LIST_RESPONSE ='LIST_RESPONSE';
